version: '3.8'
services:
  app:
    build: .
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db            # Use service name here
      DB_PORT: 3306
      DB_DATABASE: myattendance
      DB_USERNAME: root
      DB_PASSWORD: root      # Add your root password here
  
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: myattendance  # Match this with your DB_DATABASE
      MYSQL_ROOT_PASSWORD: root      # This password should match the one in the app service
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
